---
bibliography: references.bib
csl: styles.ref/nature.csl
output:
  bookdown::word_document2:
    reference_docx: styles.doc/NIH_grant_style.docx
---

```{r include=F}
knitr::opts_chunk$set(echo = FALSE,
                      tidy.opts=list(width.cutoff=60),
                      tidy=TRUE)
load("grant.R")
```


# Anexo 2

## Presentación de la propuesta.

**Datos del responsable Técnico : ** Dra. Ruth Selene Fuentes García. Profesor Titular “A”. Facultad de ciencias, UNAM.

**Título: ** Estimación del impacto de las medidas de mitigación por COVID-19 en las 32 entidades federativas de México utilizando un modelo jerárquico Bayesiano.

**Aim 2: **

**Aim 3: **

## Descripción del proyecto.

### Introducción y antecedentes

Los coronavirus [@arabi2020covid] son una familia de virus que suelen causar enfermedades en animales, aunque algunos pueden afectar también a humanos. En las personas pueden producir infecciones respiratorias que pueden ir desde un resfriado común hasta enfermedades más graves. En el 80% de los casos, la infección por este nuevo coronavirus, denominado oficialmente SARS-Cov-2, produce síntomas respiratorios de carácter leve. Con el nombre de COVID-19 se denomina la enfermedad respiratoria producida por este virus. Hasta el día de hoy (`r format(max(data_covid$date), "%b %e")`) se han confirmado en nuestro país `r formatC(confirmados, format="f", big.mark=",", digits=0)` casos y `r formatC(muertes, format="f", big.mark=",", digits=0)`muertes. Mucho se ha hablado de la importancia de las medidas de mitigación para tratar de frenar la epidemia y así evitar la saturación de los hositales, especialmente aquellos de tercer nivel. La razón detrás de implementar estas medidas es el número básico de reproducción $R_0$, el cual mide en promedio cuantas personas son infectadas por una persona con la infección en una población susceptible. Una consecuencia de lo anterior es que en medida en que más personas se infecten, el número de reproducción disminuirá ya que en algún punto en el futuro se lograría la inmunidad de rebaño; a causa de esta temporalidad se introduce el número de efectivo de reproducción $R_t$ [@nishiura2009effective], teniendo la misma definición que $R_0$ pero ahora a tiempo $t$.

En nuestro país, tanto los gobiernos estatales como el gobierno federal han implementado diferentes medidas de mitigación con el obtivo de disminuir $R_t$, ya que al hacerlo resultaría en un número menor de infectados por SARS-Cov-2 y en consecuencia un número menor de hospitalizaciones y muertes. Si $R_t<1$ entonces se podría afirmar que la transmisión está bajo control y por lo tanto se podrían retirar una o varias medidas de mitigación.

#### Vigilancia epidemiológica en México

La vigilancia epidemiológica en nuestro país se basa en un sistema centinela a través del sistema de Unidades de Salud Monitoras de Enfermedades Respiratorias (USMER), adoptado desde el año 2006. El objetivo de las unidades es brindar información epidemiológica de varios virus (e.g. influenza) de forma oportuna y completa, sin olvidar que éste no tiene como objetivo recopilar los casos completos en el país sino privilegiar la calidad de la información recopilada en estas unidades [@deguia]. El 28 de febrero se confirmó el primer individuo con CoVID-19 en nuestro país, desde entonces se ha actualizado la definición operacional (siendo el 23 de marzo la última actualización) para casos sospechosos y casos confirmados:

* Caso sospechoso - Persona de cualquier edad que en los últimos siete días haya presentado al menos dos síntomas de tos, fiebre o cefalea, es decir, dolor de cabeza intenso y persistente y que esté acompañado de los siguientes signos: dificultad para respirar, hinchazón en articulaciones con dificultad de movimiento, dolor muscular, ardor de garganta, rinorrea, conjuntivitis y dolor de tórax.

* Caso confirmado - Persona que cumpla lo anterior y que cuente con confirmación del InDRE.

Asimismo, se modificó el porcentaje de muestreo para vigilar los casos de COVID-19. Solo se realizará la prueba al 10% de los casos sospechosos sin síntomas o síntomas leves. A su vez, se realizará la prueba al 100% de los casos sospechosos con sintomatología grave o que cumplan con la definición infección respiratoria aguda grave (IRAG).

#### Características de los pacientes graves con COVID-19

Se estima que aproximadamente un 5% de los casos confirmados por cOVID-19 requerirán de cuidados intensivos [@murthy2020care]. Lo anterior ha mostrado que ciertos países en el mundo experimentaran un rápido incremento en la utilización de recursos sanitarios, sobre todo aquellos países con una proporción importante de adultos mayores de 65 años [@remuzzi2020covid]. Si bien es cierto que en nuestro país solamente el 7.25% de la población pertenece a este grupo de edad (OCDE), la evidencia en otros países ha revelado que la obesidad y sus comorbilidades asociadas son un factor de riesgo importante para aquellas personas menores de 60 años [@lighter2020obesity]. Lighter et al. encontraron que [-@lighter2020obesity] aquellos pacientes menores a 60 años con índice de masa corporal (IMC) de entre 30 y 34 que ingresaron a urgencias por COVID-19 tuvieron 1.8 más posibilidades de ingresar a terapia intensiva en comparación con aquellos pacientes sin obesidad (IMC<30); estas posibilidades aumentaron a 3.6 en aquellos pacientes con un IMC mayor o igual a 35.

De acuerdo a la más reciente Encuesta Nacional de Nutrición (ENSANUT 2018) realizada conjuntamente entre el Instituto Nacional de Salud Pública (INSP) y el Instituto Nacional de Estadística y Geografía (INEGI), aproximadamente 15.2 millones de mexicanos tienen diagnóstico previo de hipertensión mientras que el 75.2% de la población mayor a 2 años tiene obesidad y sobrepeso [@romero2019encuesta]. Asimsimo la Secretaria de Salud ha reportado en sus informes técnicos diarios que los 3 principales grupos en riesgo de presentar complicaciones por COVID-19 son: personas mayores a 65 años, personas con Diabetes Mellitus (diagnosticada y no diagnosticada) y personas con hipertensión arterial.

Lo anterior se ha visto reflejado en las muertes de pacientes confirmados con COVID-19 en México [@gobmx]; hasta el 20 de abril del presente año se habían presentado 686 defunciones, siendo hipertensión, diabetes y obesidad las comorbilidades más asociadas con las defunciones (43.1%, 38.3% y 31.4% respectivamente). Debido a la epidemia de enfermedades no transmisibles que existe en nuestro país desde hace tiempo, es posible que México experimente un número alto de defunciones debido a los factores antes mencionados ya que aumentan el riesgo de complicar esta enfermedad.

#### Modelo Bayesiano semi-mecanístico

Muchos de los modelos epidemiológicos se basan en la incidencia de **casos confirmados** para poder hacer estimaciones y/o proyecciones de diferentes desenlaces en salud, ya sea mortalidad, hospitalizaciones, intubaciones, etc. Una de las grandes limitaciones es el tiempo que pasa entre el momento de la infección y el momento que la prueba resulta positiva. Esto se debe a que entre estos dos momentos hay un periodo de incubación (mediana 6 días [@lauer2020incubation]) y un periodo entre que se toma la prueba y se entrega el resultado de ésta (mediana 9 días [@gob]). Una consecuencia de esto es que los casos confirmados que se presentan día a día son en realidad los casos que se infectaron hace 2 semanas o más.
Adicionalmente, el sistema de vigilancia centinela no realiza pruebas a aquellos que no cumplen la definición operacional, implicando que este sistema no logra capturar a todas las personas asintomáticas. Esto pudiera generar diferentes brotes ya que existe evidencia científica relacionada a la transmisión del virus por parte de los que no presentan ningun tipo de síntoma [@Bai]. Debido a estas limitaciones, diferentes investigadores en enfermedades infecciosas han utilizado las muertes observadas como la variable principal para hacer inferencia en diferentes modelos epidemiológicos ([@flaxman2020report]). 

Por lo tanto, proponemos estimar el impacto que han tenido las medidas de mitigación en el número diario de infecciones por SARS-Cov-2, en el número de pacientes que requriran terapia intensiva y finalmente en el número de muertes, utilizando las **muertes diarias** como la variable observable en nuestro análisis Utilzaremos un modelo jerárquico Bayesiano semi-mecanístico^[Es semi-mecanístico ya que utiliza la estructura de los modelos compartimentales pero sin la necesidad de especificar el sistema de ecuaciones diferenciales] [@staff2019correction] debido a que las muertes observadas diarias dependen de las hopitalizaciones en terapia intensiva, éstas a su vez dependerán del número de infecciones por SARS-Cov2 que está incluenciado por el número efectivo de reproducción. Una ventaja de este tipo de modelos semi-mecanísticos es que los parámetros a estimar están influenciados por la variable observable y por lo tanto ésta representa un peso importante la momento de realizar la inferencia.

Nuestro modelo es una adaptación de un modelo epidemiológico europeo que midió el mismo desenlace en 14 países diferentes [-@flaxman2020report]; nuestra propuesta se basa en modficar algunos parámetros y adaptarlo para que la inferencia y proyecciones resulten en dos productos finales:

1. Producto a nivel estatal.
2. Producto a nivel zona metropolitana del Valle de México.

## Justificación

Gracias a que contamos con información respecto a lo que ha ocurrido en otros países, le evidencia ha mostrado [] que si se logra reducir $R_t$ esto se traducirá en menos infecciones y por lo tanto en menos muertes. La misma evidencia también ha mostrado que diferentes medidas masivas de mitigación resultan en una reducción de este número. Nuestro modelo utilizará información sobre estas medidas masivas implementadas en los estados de la república mexicana para estimar que impacto tienen estas medidas en $R_t$ (y en consecuencia el impacto que tienen en los otros parámetros del modelo).

El modelo tendrá como resultado final 


# Significance

# Innovation

# Approach 

## Overall strategy

## Aim 1: 

### Limitations and alternatives

## Aim 2: 

## Aim 3: 

# Timeline

# References
